/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualan.UI;

import helper.ConnnectionHelper;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import static penjualan.UI.laporanApp.KueList;
import static penjualan.UI.laporanApp.tableModel;
import penjualan.manager.PemesananManajer;
import penjualan.manager.ProdukManajer;
import penjualan.model.pemesanan;
import penjualan.model.produk;

/**
 *
 * @author L
 */
public class MainApp extends javax.swing.JFrame {

    int x = 0;

    /**
     * Creates new form MainApp
     */
    public MainApp() {
        initComponents();
        tampil_kue();
        aturTextField();

//        autoSum();
        //ke tabel pemesanan
        //supaya tidak bisa di resize
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);

    }

    public void tampil_kue() {
        try {
            String query = "SELECT Nama_kue FROM produk order by Nama_kue asc";
            Connection conn = ConnnectionHelper.getConnection();
            Statement stm = conn.createStatement();

            ResultSet rs = stm.executeQuery(query);

            while (rs.next()) {
                Object[] ob = new Object[3];
                ob[0] = rs.getString(1);

                cmbPilihKue.addItem((String) ob[0]);

            }
            rs.close();
            stm.close();
            rs.last();
            int jumlahdata = rs.getRow();
            rs.first();

        } catch (Exception e) {
        }
    }

    public void tampil() {
        try {
            String query = "SELECT id_kue, Harga_kue, Stock_kue FROM produk where Nama_kue='" + cmbPilihKue.getSelectedItem() + "'";
            Connection conn = ConnnectionHelper.getConnection();
            Statement stm = conn.createStatement();

            ResultSet rs = stm.executeQuery(query);

            while (rs.next()) {
                Object[] ob = new Object[3];
                ob[0] = rs.getString(1);
                ob[1] = rs.getString(2);
                ob[2] = rs.getString(3);

                jtfIdKue.setText((String) ob[0]);
                jtfHarga.setText((String) ob[1]);
                jtfStock.setText((String) ob[2]);

            }
            rs.close();
            stm.close();
            rs.last();
            int jumlahdata = rs.getRow();
            rs.first();

        } catch (Exception e) {
        }
    }

    void aturTextField() {
        jtfHarga.setEnabled(false);
        jtfStock.setEnabled(false);
        jtfTotal.setEnabled(false);
        jtfAllTotal.setEnabled(false);
        jtfIdKue.setEnabled(false);
    }

    private void sum() {
        DefaultTableModel paymentModel = (DefaultTableModel) paymentTable.getModel();
        int jumlah = paymentModel.getRowCount();
        double Total = 0;

        for (int i = 0; i < jumlah; i++) {
            Double total = Double.valueOf(paymentModel.getValueAt(i, 3).toString());
            Total += total;
        }
        jtfAllTotal.setText(Double.toString(Total));
    }

    private void bersih() {

    }

//    public void autoSum() {
////    menjumlahkan pada kolom 4
//        int total = 0;
//        for (int i = 0; i < paymentTable.getRowCount(); i++) {
//            int amount = Integer.parseInt((String) paymentTable.getValueAt(i, 3));
//            total += amount;
//        }
//        jtfAllTotal.setText(" "+ total);
//
//    }
    public void showMessage(String message, int type) {
        if (type == 1) {
            JOptionPane.showMessageDialog(this, message, "Sukses", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        BodyPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        btnHome = new javax.swing.JToggleButton();
        btnBelanja = new javax.swing.JToggleButton();
        btnPayment = new javax.swing.JToggleButton();
        btnLogout = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        belanjaPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jtfTotal = new javax.swing.JTextField();
        jtfHarga = new javax.swing.JTextField();
        cmbPilihKue = new javax.swing.JComboBox<>();
        btnTambah = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jtfStock = new javax.swing.JTextField();
        tanggalLabel = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jtfIdKue = new javax.swing.JTextField();
        jtfPesan = new javax.swing.JTextField();
        jdtTanggal = new com.toedter.calendar.JDateChooser();
        btnProsesTotal = new javax.swing.JButton();
        payPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        paymentTable = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jtfAllTotal = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtBayar = new javax.swing.JTextField();
        btnBayar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nayla Bakery");

        BodyPanel.setBackground(new java.awt.Color(255, 204, 204));

        menuPanel.setBackground(new java.awt.Color(255, 204, 204));
        menuPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        btnHome.setBackground(new java.awt.Color(255, 153, 153));
        btnHome.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnHome.setIcon(new javax.swing.ImageIcon("E:\\Mata Kuliah\\Sem 2\\5. Pemrograman berbasis dekstop\\Logo\\Your home.png")); // NOI18N
        btnHome.setText("HOME");
        btnHome.setBorder(null);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnBelanja.setBackground(new java.awt.Color(255, 153, 153));
        btnBelanja.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnBelanja.setIcon(new javax.swing.ImageIcon("E:\\Mata Kuliah\\Sem 2\\5. Pemrograman berbasis dekstop\\Logo\\yourshop.png")); // NOI18N
        btnBelanja.setText("BELANJA");
        btnBelanja.setBorder(null);
        btnBelanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBelanjaActionPerformed(evt);
            }
        });

        btnPayment.setBackground(new java.awt.Color(255, 153, 153));
        btnPayment.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnPayment.setIcon(new javax.swing.ImageIcon("E:\\Mata Kuliah\\Sem 2\\5. Pemrograman berbasis dekstop\\Logo\\yourpay.png")); // NOI18N
        btnPayment.setText("PAYMENT");
        btnPayment.setBorder(null);
        btnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 153, 153));
        btnLogout.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon("E:\\Mata Kuliah\\Sem 2\\5. Pemrograman berbasis dekstop\\Logo\\yourout.png")); // NOI18N
        btnLogout.setText("LOGOUT");
        btnLogout.setBorder(null);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\Mata Kuliah\\Sem 2\\5. Pemrograman berbasis dekstop\\Logo\\logo (1)\\logo\\logo.jpg")); // NOI18N

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBelanja, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(80, 80, 80))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBelanja, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        mainPanel.setBackground(new java.awt.Color(255, 204, 204));
        mainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        mainPanel.setLayout(new java.awt.CardLayout());

        homePanel.setBackground(new java.awt.Color(255, 204, 204));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("SELAMAT DATANG DI");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("NAYLA BAKERY");

        jLabel4.setText(" ");

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(jLabel4))
                .addContainerGap(211, Short.MAX_VALUE))
        );

        mainPanel.add(homePanel, "card2");

        belanjaPanel.setBackground(new java.awt.Color(255, 204, 204));

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel13.setText("Nama Kue");

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel14.setText("Harga Kue");

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel15.setText("Pesan");

        jLabel16.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel16.setText("Total harga");

        jtfTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTotalActionPerformed(evt);
            }
        });

        cmbPilihKue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-" }));
        cmbPilihKue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPilihKueActionPerformed(evt);
            }
        });

        btnTambah.setText("Tambah");
        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahMouseClicked(evt);
            }
        });
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel19.setText("Stock");

        jtfStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfStockActionPerformed(evt);
            }
        });

        tanggalLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        tanggalLabel.setText("Tanggal");

        namaKonsumen.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        namaKonsumen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        idKonsumen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel20.setText("ID");

        jtfPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPesanActionPerformed(evt);
            }
        });
        jtfPesan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPesanKeyReleased(evt);
            }
        });

        btnProsesTotal.setText("Proses Total");
        btnProsesTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout belanjaPanelLayout = new javax.swing.GroupLayout(belanjaPanel);
        belanjaPanel.setLayout(belanjaPanelLayout);
        belanjaPanelLayout.setHorizontalGroup(
            belanjaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(belanjaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(belanjaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(belanjaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(belanjaPanelLayout.createSequentialGroup()
                            .addGroup(belanjaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(belanjaPanelLayout.createSequentialGroup()
                                    .addGroup(belanjaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel13))
                                    .addGap(25, 25, 25))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, belanjaPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addGap(37, 37, 37)))
                            .addGroup(belanjaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtfHarga)
                                .addComponent(cmbPilihKue, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfStock)
                                .addComponent(namaKonsumen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, belanjaPanelLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idKonsumen, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(105, 105, 105))
                                .addComponent(jtfPesan))))
                    .addGroup(belanjaPanelLayout.createSequentialGroup()
                        .addGroup(belanjaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(tanggalLabel))
                        .addGap(18, 18, 18)
                        .addGroup(belanjaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(jdtTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(belanjaPanelLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfIdKue, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProsesTotal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        belanjaPanelLayout.setVerticalGroup(
            belanjaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(belanjaPanelLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(idKonsumen, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(belanjaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(belanjaPanelLayout.createSequentialGroup()
                        .addComponent(namaKonsumen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(belanjaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfIdKue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(belanjaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(cmbPilihKue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(belanjaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jtfHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(belanjaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jtfPesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(belanjaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(belanjaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(belanjaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnProsesTotal))
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addComponent(tanggalLabel))
                    .addComponent(jdtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        mainPanel.add(belanjaPanel, "card4");

        payPanel.setBackground(new java.awt.Color(255, 204, 204));

        paymentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Konsumen", "ID Kue", "Nama", "Total", "Tanggal"
            }
        ));
        jScrollPane1.setViewportView(paymentTable);

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel17.setText("Total Harga");

        jtfAllTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAllTotalActionPerformed(evt);
            }
        });
        jtfAllTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfAllTotalKeyReleased(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel21.setText("Total Bayar");

        btnBayar.setText("Bayar");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout payPanelLayout = new javax.swing.GroupLayout(payPanel);
        payPanel.setLayout(payPanelLayout);
        payPanelLayout.setHorizontalGroup(
            payPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
            .addGroup(payPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(payPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(payPanelLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(jtfAllTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(payPanelLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, payPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBayar)
                .addGap(35, 35, 35))
        );
        payPanelLayout.setVerticalGroup(
            payPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payPanelLayout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(payPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jtfAllTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(payPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnBayar)
                .addGap(84, 84, 84))
        );

        mainPanel.add(payPanel, "card5");

        javax.swing.GroupLayout BodyPanelLayout = new javax.swing.GroupLayout(BodyPanel);
        BodyPanel.setLayout(BodyPanelLayout);
        BodyPanelLayout.setHorizontalGroup(
            BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BodyPanelLayout.setVerticalGroup(
            BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BodyPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BodyPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBelanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBelanjaActionPerformed
        // TODO add your handling code here:
        //remoce panel sebelumnya
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        // add panel selanjutnya
        mainPanel.add(belanjaPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnBelanjaActionPerformed

    private void jtfTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTotalActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:

        try {
            paymentTable.setValueAt(idKonsumen.getText(), x, 0);
            paymentTable.setValueAt(jtfIdKue.getText(), x, 1);
            paymentTable.setValueAt(namaKonsumen.getText(), x, 2);
            paymentTable.setValueAt(jtfTotal.getText(), x, 3);
            paymentTable.setValueAt(jdtTanggal.getDate(), x, 4);
            x = x + 1;

            if (jtfPesan.getText().equals("")) {
                JOptionPane.showMessageDialog(null, " Tidak Boleh Kosong");
            } else if (jtfTotal.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Tidak Boleh Kosong");
            } else if (jdtTanggal.getDate().equals("")) {
                JOptionPane.showMessageDialog(null, "Tidak Boleh Kosong");

            } else {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }

            jtfPesan.setText("");
            jtfTotal.setText("");
            sum();

        } catch (Exception e) {
            System.out.println("Error" + e.getMessage());
        }

    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentActionPerformed
        // TODO add your handling code here:
        //remoce panel sebelumnya
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        // add panel selanjutnya
        mainPanel.add(payPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnPaymentActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Apakah Anda Yakin?", "PERINGATAN", dialogBtn);

        if (dialogResult == 0) {
            // pasang true kondisi
            System.exit(0);
        } else {
            // false kondisi
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void jtfStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfStockActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        //remoce panel sebelumnya
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        // add panel selanjutnya
        mainPanel.add(homePanel);
        mainPanel.repaint();
        mainPanel.revalidate();

    }//GEN-LAST:event_btnHomeActionPerformed

    private void cmbPilihKueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPilihKueActionPerformed
        // TODO add your handling code here:
        tampil();

    }//GEN-LAST:event_cmbPilihKueActionPerformed

    private void jtfPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPesanActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jtfPesanActionPerformed

    private void jtfPesanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesanKeyReleased
        // TODO add your handling code here:


    }//GEN-LAST:event_jtfPesanKeyReleased

    private void jtfAllTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAllTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfAllTotalActionPerformed

    private void jtfAllTotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfAllTotalKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jtfAllTotalKeyReleased

    private void btnTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnTambahMouseClicked

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        // TODO add your handling code here:
        try {
            java.sql.Connection conn = ConnnectionHelper.getConnection();
            Statement stmn = conn.createStatement();

            String query1 = "INSERT INTO pemesanan (`id_konsumen`,`id_kue`, `Nama_konsumen`,`Total_harga`, `Tanggal_pemesanan`) "
                    + "VALUES ('" + idKonsumen.getText() + "', '" + jtfIdKue.getText() + "', "
                    + "'" + namaKonsumen.getText() + "', '" + jtfAllTotal.getText() + "', '" + jdtTanggal.getDate() + "')";

            String query2 = "INSERT INTO pembayaran (`Total_bayar`, `Tanggal_pembayaran`) "
                    + "VALUES ('" + txtBayar.getText() + "', '" + jdtTanggal.getDate() + "')";

            stmn.executeUpdate(query1);
            stmn.executeUpdate(query2);

            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            System.out.println("Error" + e.getMessage());
        }

    }//GEN-LAST:event_btnBayarActionPerformed

    private void btnProsesTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesTotalActionPerformed
        // TODO add your handling code here:
        double hargabarang, total;
        int jumlahbeli, stock;

        hargabarang = Double.parseDouble(jtfHarga.getText());
        jumlahbeli = Integer.parseInt(jtfPesan.getText());
        stock = Integer.parseInt(jtfStock.getText());

        if (stock < jumlahbeli) {
            JOptionPane.showMessageDialog(this, "Stok tidak mencukupi", "Maaf", JOptionPane.INFORMATION_MESSAGE);
            jtfPesan.setText("");
        } else {
            total = hargabarang * jumlahbeli;
            jtfTotal.setText(" " + total);
        }


    }//GEN-LAST:event_btnProsesTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BodyPanel;
    private javax.swing.JPanel belanjaPanel;
    private javax.swing.JButton btnBayar;
    private javax.swing.JToggleButton btnBelanja;
    private javax.swing.JToggleButton btnHome;
    private javax.swing.JToggleButton btnLogout;
    private javax.swing.JToggleButton btnPayment;
    private javax.swing.JButton btnProsesTotal;
    private javax.swing.JButton btnTambah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbPilihKue;
    private javax.swing.JPanel homePanel;
    public static final javax.swing.JLabel idKonsumen = new javax.swing.JLabel();
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdtTanggal;
    private javax.swing.JTextField jtfAllTotal;
    private javax.swing.JTextField jtfHarga;
    private javax.swing.JTextField jtfIdKue;
    private javax.swing.JTextField jtfPesan;
    private javax.swing.JTextField jtfStock;
    private javax.swing.JTextField jtfTotal;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    public static final javax.swing.JLabel namaKonsumen = new javax.swing.JLabel();
    private javax.swing.JPanel payPanel;
    private javax.swing.JTable paymentTable;
    private javax.swing.JLabel tanggalLabel;
    private javax.swing.JTextField txtBayar;
    // End of variables declaration//GEN-END:variables
}
